matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: yakkety
      sudo: required
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install doxygen; fi

script:
  - |-
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget -qO - https://raw.githubusercontent.com/hrektts/setup/${TRAVIS_BRANCH}/setup.sh | sh -s -- ${TRAVIS_BRANCH}
    fi
  - |-
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      curl -sSf https://raw.githubusercontent.com/hrektts/setup/${TRAVIS_BRANCH}/setup.sh | sh -s -- ${TRAVIS_BRANCH}
    fi
