---
- name: "Add Homebrew Cask repositories"
  homebrew_tap:
    tap: "{{ item }}"
    state: "present"
  with_items: "{{ homebrew_cask_repositories }}"

- name: "Update homebrew"
  command: "brew cask update"

- name: "Install/Upgrade Homebrew Cask fomula"
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_cask_packages }}"

- name: "Cleanup packages"
  command: "brew cask cleanup"

- name: "Check soundness"
  command: "brew cask doctor"
