---
- name: "Add Homebrew repositories"
  homebrew_tap:
    tap: "{{ item }}"
    state: "present"
  with_items: "{{ homebrew_repositories }}"

- name: "Update Homebrew and upgrade all packages"
  homebrew:
    update_homebrew: "yes"
    upgrade_all: "yes"

- name: "Install/Upgrade Homebrew formula"
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default('omit') | join(',') }}"
  with_items: "{{ homebrew_packages }}"

- name: "Create symlinks"
  command: "brew linkapps"

- name: "Cleanup packages"
  command: "brew cleanup"

- name: "Check soundness"
  command: "brew doctor"
